@startuml
title __Alice share UMA resource__
autonumber
Alice -> AM : Authenticate, get PAT
AM --> Alice : PAT

Alice -> IG_UMA_RS : Share UMA resource using PAT
IG_UMA_RS -> AM : Create UMA resource
IG_UMA_RS -> DS : Persist UMA resource
IG_UMA_RS --> Alice : Resource created (Both on AM and D)

Alice -> IG_UMA_RS : List all UMA resources using PAT
IG_UMA_RS --> Alice : UMA resources

Alice -> IG_UMA_RS : Read specific UMA resource using PAT
IG_UMA_RS --> Alice : UMA resource

@enduml